workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,6 +21,15 @@ jobs:
       env:
         REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
         REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
+
+    - name: Check Build Output
+        run: grep REACT_APP_STRAVA_CLIENT_ID build/static/js/*.js || echo "Client ID not found in build output"
+
+    - name: Debug
+      run: |
+        echo "Client ID is set: ${{ env.REACT_APP_STRAVA_CLIENT_ID != '' }}"
+        echo "Client Secret is set: ${{ env.REACT_APP_STRAVA_CLIENT_SECRET != '' }}"
+
     
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
