Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,14 +1,15 @@
-name: CI/CD
-
+name: Build and Deploy
 on:
   push:
-    branches: [ main ]
-  pull_request:
     branches: [ main ]
 
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
+
+    env:
+      REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
+      REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
     
     steps:
     - uses: actions/checkout@v2
@@ -16,24 +17,58 @@ jobs:
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
-        node-version: '14'
+        node-version: '14'  # or your preferred Node.js version
+
+    - name: Change to project directory
+      run: cd stram
 
     - name: Install Dependencies
-      run: npm ci
+      working-directory: ./stram
+      run: npm ci  # Using 'npm ci' for more reliable builds
 
-    - name: Set Environment Variables
+    - name: Set and Check Environment Variables
       run: |
         echo "REACT_APP_STRAVA_CLIENT_ID=${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}" >> $GITHUB_ENV
         echo "REACT_APP_STRAVA_CLIENT_SECRET=${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}" >> $GITHUB_ENV
-
+        if [ -z "${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_ID is not set in GitHub Secrets"
+          exit 1
+        fi
+        if [ -z "${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_SECRET is not set in GitHub Secrets"
+          exit 1
+        fi
+    
     - name: Build
-      run: npm run build
+      working-directory: ./stram
       env:
         REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
         REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
+      run: |
+        echo "Building with REACT_APP_STRAVA_CLIENT_ID: $REACT_APP_STRAVA_CLIENT_ID"
+        CI=false npm run build
+
+    - name: Check Build Output
+      working-directory: ./stram
+      run: |
+        grep -r REACT_APP_STRAVA_CLIENT_ID build/static/js || echo "Client ID not found in build output"
+        cat build/static/js/main.*.js | grep REACT_APP_STRAVA_CLIENT_ID || echo "Client ID not found in main JS file"
+
+    - name: Debug
+      run: |
+        if [ -n "$REACT_APP_STRAVA_CLIENT_ID" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_ID is set"
+        else
+          echo "REACT_APP_STRAVA_CLIENT_ID is not set"
+        fi
+        if [ -n "$REACT_APP_STRAVA_CLIENT_SECRET" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_SECRET is set"
+        else
+          echo "REACT_APP_STRAVA_CLIENT_SECRET is not set"
+        fi
 
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./build
+        publish_dir: ./stram/build
