Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,56 +1,41 @@
-name: Build and Deploy
-on:
-  push:
-    branches: [ main ]
-
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
-
-    env:
-      REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
-      REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
     
     steps:
     - uses: actions/checkout@v2
 
-    - name: Change to project directory
-      run: cd stram
+    - name: Set and Check Environment Variables
+      run: |
+        echo "REACT_APP_STRAVA_CLIENT_ID=${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}" >> $GITHUB_ENV
+        echo "REACT_APP_STRAVA_CLIENT_SECRET=${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}" >> $GITHUB_ENV
+        if [ -z "${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_ID is not set in GitHub Secrets"
+          exit 1
+        fi
+        if [ -z "${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}" ]; then
+          echo "REACT_APP_STRAVA_CLIENT_SECRET is not set in GitHub Secrets"
+          exit 1
+        fi
 
     - name: Install Dependencies
       working-directory: ./stram
       run: npm install
 
-    - name: Set Environment Variables
-      run: |
-        echo "REACT_APP_STRAVA_CLIENT_ID=${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}" >> $GITHUB_ENV
-        echo "REACT_APP_STRAVA_CLIENT_SECRET=${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}" >> $GITHUB_ENV
-    
     - name: Build
       working-directory: ./stram
       env:
         REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
         REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
-      run: CI=false npm run build
+      run: |
+        echo "Building with REACT_APP_STRAVA_CLIENT_ID: $REACT_APP_STRAVA_CLIENT_ID"
+        CI=false npm run build
 
     - name: Check Build Output
       working-directory: ./stram
-      run: grep REACT_APP_STRAVA_CLIENT_ID build/static/js/*.js || echo "Client ID not found in build output"
-
-    - name: Debug
       run: |
-        if [ -n "$REACT_APP_STRAVA_CLIENT_ID" ]; then
-          echo "REACT_APP_STRAVA_CLIENT_ID is set"
-        else
-          echo "REACT_APP_STRAVA_CLIENT_ID is not set"
-        fi
-        if [ -n "$REACT_APP_STRAVA_CLIENT_SECRET" ]; then
-          echo "REACT_APP_STRAVA_CLIENT_SECRET is set"
-        else
-          echo "REACT_APP_STRAVA_CLIENT_SECRET is not set"
-        fi
+        grep -r REACT_APP_STRAVA_CLIENT_ID build/static/js || echo "Client ID not found in build output"
 
-    
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       with:
